apiVersion: numaplane.numaproj.io/v1alpha1
kind: PipelineRollout
metadata:
  name: my-pipeline
spec:
  pipeline:
    edges:
    - from: in
      to: cat
    - from: cat
      to: out
    interStepBufferServiceName: my-isbsvc
    vertices:
    - name: in
      source:
        generator:
          duration: 1s
          rpu: 5
    - name: cat
      udf:
        builtin:
          name: cat
    - name: out
      sink:
        log: {}
